### ISSUE TITLE
SSO en boucle

### ISSUE THREAD

**Issue by LeOSW42** [YunoHost-Apps/gogs_ynh_old#1]
Voilà l'erreur que j'ai :

> La page n'est pas redirigée correctement
> 
> Firefox a détecté que le serveur redirige la demande pour cette adresse d'une manière qui n'aboutira pas.
> 
> ```
> La cause de ce problème peut être la désactivation ou le refus des cookies.
> ```

Léo

**Comment by matlink** [comment]
Pareil. Je crois que le service Gogs réécris les URL en supprimant le sous dossier.
Genre nginx proxy domain.fr/gogs vers localhost:3000, du coup gogs vire le /gogs et redirige vers domain.fr/install, d'où le SSO.
