### ISSUE TITLE
Every YunoHost LDAP user can connect.

### ISSUE THREAD

**Issue by M5oul** [YunoHost-Apps/gogs_ynh_old#13]
Every YunoHost user can log-in and create repositories to Gogs. It also works with SSOwat blockage.

It could be a great feature, to remove access to them, If the administrator of the YunoHost instance doesn't want it.

I think removing account from Gogs interface could be a solution. But, I fear it will break LDAP YunoHost accounts.

**Comment by stevenroose** [comment]
Why would you want to block some users from the app? I don't think it's necessary to do this here, you could make a similar inquiry for every packaged YunoHost app, not a single one will be able to do this by default..

**Comment by M5oul** [comment]
Yep, it's tricky.

**Comment by mbugeia** [comment]
I agree with @stevenroose that this is the desired behavior. In a better world Gogs should have a greater granularity of permissions (like non LDAP user should have the right to open issue) but unfortunatly that's not the case.

Deleting a user in Gogs panel won't break LDAP Yunohost account but it will be re-created every time the user try to connect to Gogs so it's useless. But it you block an user from accessing Gogs with SSOwat it should work but it will no longer have access to public repo either.
