### ISSUE TITLE
"This webpage has a redirect loop"

### ISSUE THREAD

**Issue by stevenroose** [YunoHost-Apps/gogs_ynh_old#14]
I installed Gogs on the root of one of my domains, and it gave a redirect error.

The root domain, `example.org` was redirected to `example.org//`, so I guess there is an error in the path substitution, I've fixed that for several apps before, because none of them seem to be optimised for use on a naked domain. Will look at this.

**Comment by mbugeia** [comment]
Fixed and tested in dev branche
