### ISSUE TITLE
Pour le LDAP

### ISSUE THREAD

**Issue by LeOSW42** [YunoHost-Apps/gogs_ynh_old#2]
Salut,

Voilà la config qui je pense est la bonne :

```
{"Name":"ldap","Host":"localhost","Port":389,"UseSSL":false,"BaseDN":"dc=yunohost,dc=org","Attributes":"uid","Filter":"(\u0026(|(objectclass=mailAccount))(uid=%s))","MsAdSAFormat":"cn=%s,dc=yunohost,dc=org","Enabled":true}
```

**Comment by mbugeia** [comment]
Ça n'a pas l'air de fonctionner pour moi, je n'arrive pas à me logger avec un utilisateur du ldap.

**Comment by LeOSW42** [comment]
Effectivement moi non plus, je ne sais pas si c'est parce que le sso est en conflit avec LDAP...

**Comment by mbugeia** [comment]
Le SSO fonctionne parfaitement, j'ai testé avec un autre user local, on est bien automatiquement connecté si le user existe dans la base de l'appli.

Pour info le SSO se contente de passer un header http REMOTE_USER à l'appli qui supporte l'authentification basique http, l'appli recherche dans ça base si le user existe et s'il existe le connecte.

L'idée étant que la base de users utilisée par l'appli soit celle celle du ldap et non sa base "locale", je ne pense pas qu'il y ait de conflit entre les deux. Mais il faut trouver la bonne config ldap...

**Comment by mbugeia** [comment]
Issue du projet sur le même thème qu'il sera intéressante de suivre :
https://github.com/gogits/gogs/issues/672

**Comment by mbugeia** [comment]
Tout devrait fonctionner depuis la dernière update #10
