### ISSUE TITLE
Add precise login instructions to README/manifest

### ISSUE THREAD

**Issue by ghost** [YunoHost-Apps/gogs_ynh_old#23]
One of these files should precise that it is necessary to use yunohost credentials to login and not the password set during the install (which is for sql I guess ?).  

---

Un de ces fichiers devrait préciser qu'il est nécessaire d'utiliser les identifiants yunohost pour se connecter, et non ceux précisés pendant l'installation.

**Comment by mbugeia** [comment]
Hi,
you should be logged in automatically with the sso, is that not the case ?

Anyway the way gogs administrator was created was not good at all. To be admin the password you give at the install must match the password of your yunohost user. This was not precised.

I changed that with the last 2 commit and now only the admin login name is required. You can update but unfortunatly this will not update admin badly created so you have to do it manually. Let me know if you have issue and want help for that.

**Comment by ghost** [comment]
Er, yeah sure, but I meant that it's not obvious on first login that one would login with ynh credentials and not with the password asked during the install :}  
But eh, not it's fixed :+1: 

Well, my password is indeed different, what can I do to fix my admin ? I kinda want to fix that before any update goes wild eheh

**Comment by n00dl3** [comment]
@roylockhart :
open mysql client :

``` bash
mysql -uroot -p$(cat /etc/yunohost/mysql)
```

then use gogs db and set admin rights to the user "username" :

``` SQL
use gogs;
update user set is_admin=1 where lower_name="username";
```

enjoy admin rights !

**Comment by mbugeia** [comment]
Thanks @n00dl3 that's indeed the proper solution.

**Comment by ghost** [comment]
Thanks @n00dl3 !

I guess we can close this ?

**Comment by stevenroose** [comment]
@roylockhart Perhaps put in on the README

**Comment by mbugeia** [comment]
@stevenroose it's not necessary, the issue is fixed now.
