### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by skitoo** [YunoHost-Apps/gogs_ynh_old#24]
Hi,

I installed gogs on my raspberrypi, but when I want to go to gogs I have a 502 Bad Gateway error.

How can fix this problem ? 

Thank you.

**Comment by mbugeia** [comment]
Hi,
502 error are generic error so I need more details. Gogs is probably not started.

Can you provide the installation log ? Are you on debian Wheezy or Jessie ?

**Comment by mbugeia** [comment]
Closed because of lack of feedback
