### ISSUE TITLE
Decrease log level

### ISSUE THREAD

**Issue by n00dl3** [YunoHost-Apps/gogs_ynh_old#27]
By default gogs use the `Trace` level which is IMHO really too verbose, as it keeps logs of every db request, which means wasting I/O for non-development environment.
I decreased it to `Info` for my own installation.

**Comment by mbugeia** [comment]
I agree

**Comment by stevenroose** [comment]
Fixed by https://github.com/stevenroose/gogs_ynh/commit/607a5ac8daa5470d0890a281d3c86e0d4c62ff70 in my master (required #40).

**Comment by mbugeia** [comment]
Fixed on the new repo https://github.com/YunoHost-Apps/gogs_ynh
