### ISSUE TITLE
Package is heavy to download

### ISSUE THREAD

**Issue by M5oul** [YunoHost-Apps/gogs_ynh_old#29]
The git repository is growing in memory size. It actually weigh ~200Mo as sources only weigh ~20Mo.
I think previous tarballs containing sources are stocked in `.git`

I think this issue come from that [[fr] git limitation](https://fr.wikipedia.org/wiki/Logiciel_de_gestion_de_versions#Limitations) on last sentence of this §.

It's long to download/install this package even with a normal internet bandwidth.

Creating a new repository and loosing git history? Before, I think old tarballs could be deleted from `.git`.

Similar issues on StackOverFlow: [one](https://stackoverflow.com/questions/25550597/git-how-to-remove-a-large-file-from-commit-history-so-i-can-push-repository), [two](https://stackoverflow.com/questions/10622179/how-to-find-identify-large-files-commits-in-git-history).

**Comment by stevenroose** [comment]
Yeah, tarballs should not be in the repo. The install script should contain
a link to the tarball f.e. from the github release.

**Comment by mbugeia** [comment]
Yes, I have the same issue with seafile. I'm thinking about modifying the script to download the sources via git and removing tarballs from the repo.
This or keeping only the last tarballs but I don't really like loosing git history.

**Comment by stevenroose** [comment]
You cant delete previous commits that had tarballs, though. So I guess the only way to get rid of the ones in the history is by doing a `git init` and `git push origin master -f` to overwrite. That would delete history, but the repo would no longer be 200 MiB

**Comment by mbugeia** [comment]
With the tool https://rtyley.github.io/bfg-repo-cleaner/ I was able to reduce the size of the repo to 29Mo. That's much better but still not perfect.
In a next update I think I will checkout the correct gt tag in the /sources directory instead of using a zip.

**Comment by julienmalik** [comment]
You don't need to embed the sources to the ynh package.

Simply wget'ing the tarball is enough, like :

```
wget https://github.com/gogits/gogs/archive/v0.8.25.tar.gz
```

It is much easier to update to new upstream releases then.

**Comment by mbugeia** [comment]
Yes it's easier to do this but I was under the impression that a yunohost package must be "independant" and have all the sources directly in the package. Plus this way all the dependencies are packaged, with a direct download of the source a go get will be necessary and that increase the install time a lot.

There isn't any official recommendation in https://yunohost.org/#/packaging_apps I'm not sure what's the best solution here.

**Comment by julienmalik** [comment]
https://dev.yunohost.org/issues/201

**Comment by mbugeia** [comment]
I want to upgrade gogs and by the same occasion downloading source directly from github but it makes me crazy. I can't manage to build the correct version without GOPATH error. The only way I've found is to clone the repo like in the current readme but it's worst in terms of download size than the current package.

Here is my WIP

```
gogs_version=0.9.13

# Download and extract gogs sources
wget -O /tmp/v${gogs_version}.tar.gz https://github.com/gogits/gogs/archive/v${gogs_version}.tar.gz
tar -C /tmp -xzf /tmp/v${gogs_version}.tar.gz
rm -f /tmp/v${gogs_version}.tar.gz
mv /tmp/v${gogs_version} /tmp/gogs

# Build Gogs
base_directory=$PWD
export GOPATH=/tmp/gogs
cd ${GOPATH}
go get
go build

# Move binary and do some cleanup
cd ${base_directory}
rm -rf ${GOPATH}/src
final_path=/opt/${APP}
sudo mkdir -p ${final_path}
sudo mv ${GOPATH}/* ${final_path}
rm -rf ${GOPATH}
```

Does anyone have an idea ? @Josue-T maybe ?

**Comment by stevenroose** [comment]
This should be fixed by #40.

**Comment by M5oul** [comment]
On @stevenroose's branch, the `.git` is still heavy:

``` bash
~/gogs_ynh# du -hs .git
96M .git
```

If we can't find a solution to reduce this history size, we will have to start a new repository from zero.
That history could be saved on an other repository (YunoHost-Apps/gogs_old_ynh) to know what happen in the past of that package.

**Comment by mbugeia** [comment]
Fixed on the new repo https://github.com/YunoHost-Apps/gogs_ynh
