### ISSUE TITLE
Redirigé en permanence vers yunohost/sso

### ISSUE THREAD

**Issue by LeOSW42** [YunoHost-Apps/gogs_ynh_old#3]
Bonjour,

Si l'on essaye d'accéder à gogs sans être connecté, nous sommes en permanence redirigés vers le SSO, ce qui est gênant quand l'on veut par exemple partager un repo avec le public.

Léo

**Comment by mbugeia** [comment]
Oui c'est bien le comportement attendu, pour l'instant l'appli n'est que privée, j'ai l'intention de rajouter une option pour pouvoir la rendre public.

En attendant il est possible de faire ça :
sudo yunohost app setting gogs skipped_uris -v "/"
sudo yunohost app ssowatconf

**Comment by LeOSW42** [comment]
Merci pour la manip, je close ;)

**Comment by LeOSW42** [comment]
J'avouerais que ça ne marche pas, pourtant mon `/etc/yunohost/apps/gogs/settings.yml` est ok, et j'ai bien fait un reboot
