### ISSUE TITLE
Install script leaves sources around

### ISSUE THREAD

**Issue by julienmalik** [YunoHost-Apps/gogs_ynh_old#33]
Install script should clean up anything unneeded for runtime.
Currently the /opt/gogs_src is filled with source packages that I suppose are unused for runtime.

**Comment by mbugeia** [comment]
/opt/gogs_src also contain the compiled binary whose are linked to /opt/gogs https://github.com/mbugeia/gogs_ynh/blob/master/scripts/install#L62

**Comment by stevenroose** [comment]
This should be fixed by #40.

**Comment by mbugeia** [comment]
Fixed on the new repo https://github.com/YunoHost-Apps/gogs_ynh
