### ISSUE TITLE
Install script spread data is too many places

### ISSUE THREAD

**Issue by julienmalik** [YunoHost-Apps/gogs_ynh_old#34]
Currently we have :
/opt/gogs_src/src/github.com/gogits/gogs
/etc/gogs
/home/gogs
/var/log/gogs
/home/yunohost.app/gogs/

This is a lot for a non-system package.
It would be nice if as many stuff as possible could live within a single root dir (/opt/gogs ?)
Storing application data in /home/yunohost.app/gogs is a good idea, but then having gogs home in it would make sense (you could split with /home/yunohost.app/gogs/repository /home/yunohost.app/gogs/home ?).

Can you avoid /etc/gogs ? All the more since this is symlinked next to the binary.

**Comment by julienmalik** [comment]
See #33 also

**Comment by stevenroose** [comment]
The PR I submitted some time ago moves away from /opt and let's the user
chose the install path, defaulting to /var/www, which is default for
application binaries.

**Comment by mbugeia** [comment]
@julienmalik I agree, the package need a rework to use only /opt/gogs, /home/yunohost.app/gogs for data and /var/log/gogs

@stevenroose I'm sorry about your PR but It was lacking a proper migration method and there was no good reason to move the installation directory. There is no clear directive by the yunohost team to use /opt or /var/www, and from Linux FHS point of view, /opt is good. Plus letting the user chose the install path is not the way to go, no other yunohost app do this.

**Comment by julienmalik** [comment]
https://dev.yunohost.org/issues/200

**Comment by julienmalik** [comment]
Letting the user choose the install path is definitely not the way to go. This is purely internal stuff and should not be exposed.

**Comment by stevenroose** [comment]
I fixed this in my master with commit https://github.com/stevenroose/gogs_ynh/commit/607a5ac8daa5470d0890a281d3c86e0d4c62ff70.

But since I cannot test on my machine, it probably needs getting some bugs out.

**Comment by mbugeia** [comment]
Fixed on the new repo https://github.com/YunoHost-Apps/gogs_ynh
