### ISSUE TITLE
app.ini might need an update

### ISSUE THREAD

**Issue by julienmalik** [YunoHost-Apps/gogs_ynh_old#35]
Seems like it diverged from the sample https://github.com/gogits/gogs/blob/master/conf/app.ini
OAuth is disabled since 0.6.x
see also cron config.

**Comment by mbugeia** [comment]
+1 for updating the conf, cron config is ok since gogs use the default if absent from the conf file

**Comment by stevenroose** [comment]
Fixed by https://github.com/stevenroose/gogs_ynh/commit/607a5ac8daa5470d0890a281d3c86e0d4c62ff70 in my master (required #40).

**Comment by mbugeia** [comment]
Fixed on the new repo https://github.com/YunoHost-Apps/gogs_ynh
