### ISSUE TITLE
arbitrary "sleep 30" is unsafe

### ISSUE THREAD

**Issue by julienmalik** [YunoHost-Apps/gogs_ynh_old#36]
either it is too long and it is too bad.
either it is too short and you don't know about it (the rest will fail probably).

can you find a condition to check whether gogs has finished bootstraping ?
then implement a while loop around it.

**Comment by mbugeia** [comment]
Yes it's bad, I don't know any good condition I can use. Maybe some SQL to see if a specific table exist.

**Comment by mbugeia** [comment]
Fixed on the new repo https://github.com/YunoHost-Apps/gogs_ynh
