### ISSUE TITLE
Backing up source files is unnecessary

### ISSUE THREAD

**Issue by stevenroose** [YunoHost-Apps/gogs_ynh_old#41]
I was going through the backup script and I thought this piece could be removed:

``` bash
# Backup app files
sudo mkdir -p "${BACKUP_DIR}/www"
sudo cp -a "/opt/${APP}_src" "${BACKUP_DIR}/www"
```

**Comment by stevenroose** [comment]
Fixed by https://github.com/stevenroose/gogs_ynh/commit/607a5ac8daa5470d0890a281d3c86e0d4c62ff70 in my master (requires #40).

**Comment by mbugeia** [comment]
Fixed on the new repo https://github.com/YunoHost-Apps/gogs_ynh
