### ISSUE TITLE
Move Gogs to an External Drive

### ISSUE THREAD

**Issue by Oliquae** [YunoHost-Apps/gogs_ynh_old#42]
Hi,

I am currently planning to move some of my applications from the Raspberry Pi to an external drive because I feel them quite heavy -- either in taken space either by the number of writes on SD -- and Gogs is part of them. 

I am learning to code, so I'll use repositories rather often but I fear to use too much space on the SD Card. Therefore, I'd like to move it to a drive I named _blackberry_ (get it?). I am referring to the [Administrator guide](https://yunohost.org/#/admin_en) to move it but... it's not in `/var/www` ?

I asked `whereis` Gogs, and here's the output:

```
ssh-termin@l:~# whereis gogs
gogs: /etc/gogs
```

As it's not in the usual folder, would it be safe to move it to `/media/blackberry/gogs/`? Of course, I will make a symbolic link to it, and the drive is directly connected to the small machine.

**Comment by M5oul** [comment]
You could, as for many other YunoHost apps, do a symbolic link from an other memory device.
You have to use `mount` and `ln -s` commands.

If you only want to move data of gogs, not the code of gogs, they are in `/home/yunohost.app/gogs/`.

This is a personal help an not related to Gogs package.

I close it. Feel free to reopen.
