### ISSUE TITLE
Current old-stable install fail on YnH 2.4

### ISSUE THREAD

**Issue by M5oul** [YunoHost-Apps/gogs_ynh_old#43]
It was a predicted behavior, just to save logs somewhere which could help about install which fail.
I tested the old-stable version of this gogs package on YunoHost 2.4:

``` bash
Reading package lists...
+ sudo addgroup gogs --system --quiet
+ sudo adduser gogs --disabled-login --ingroup gogs --system --quiet --shell /bin/bash
+ base_directory=/var/cache/yunohost/from_file/gogs_ynh-master/scripts
+ final_path=/opt/gogs
+ export GOPATH=/opt/gogs_src
+ GOPATH=/opt/gogs_src
+ tar xzf ../sources/gogs_src.tar.gz
+ sudo mv gogs_src /opt/gogs_src
+ cd /opt/gogs_src/src/github.com/gogits/gogs
+ go build
+ cd /var/cache/yunohost/from_file/gogs_ynh-master/scripts
+ sudo ln -s /opt/gogs_src/src/github.com/gogits/gogs /opt/gogs
+ repo_path=/home/yunohost.app/gogs
+ sudo mkdir -p /home/yunohost.app/gogs
+ sudo yunohost app setting gogs repopath -v /home/yunohost.app/gogs
+ sudo mkdir -p /etc/gogs/conf
+ sudo mkdir -p /home/gogs/data/avatars
+ sudo mkdir -p /var/log/gogs
+ sudo rm -rf /opt/gogs/log
+ sudo rm -rf /opt/gogs/custom
+ sudo rm -rf /opt/gogs/data
+ sudo ln -fs /etc/gogs /opt/gogs/custom
+ sudo ln -fs /home/gogs/data /opt/gogs/data
+ sudo ln -fs /var/log/gogs /opt/gogs/log
+ sudo cp ../conf/logrotate /etc/logrotate.d/gogs
+ sudo service rsyslog restart
+ sudo cp ../conf/systemd/gogs.service /etc/systemd/system/
+ sudo systemctl daemon-reload
+ sudo systemctl enable gogs.service
Warning: Created symlink from /etc/systemd/system/multi-user.target.wants/gogs.service to /etc/systemd/system/gogs.service.
+ sudo chown gogs:gogs -R /opt/gogs_src
+ sudo chown gogs:gogs -R /opt/gogs
+ sudo chown -hR gogs:gogs /home/yunohost.app/gogs
+ sudo chown -R gogs:gogs /var/log/gogs
+ sudo chown -R gogs:gogs /home/gogs
+ sudo cp ../conf/app.ini /opt/gogs/custom/conf
Warning: cp: not writing through dangling symlink ‘/opt/gogs/custom/conf/app.ini’
Executing script '/var/cache/yunohost/from_file/gogs_ynh-master/scripts/remove'...
+ app=gogs
++ sudo yunohost app setting gogs domain
+ domain=<domain>
++ sudo cat /etc/yunohost/mysql
+ root_pwd='<passwd>'
+ sudo service gogs stop
++ sudo yunohost app setting gogs repopath
+ repo_path=/home/yunohost.app/gogs
+ sudo rm -rf /home/yunohost.app/gogs
+ sudo systemctl disable gogs.service
Warning: Removed symlink /etc/systemd/system/multi-user.target.wants/gogs.service.
+ sudo rm -rf /etc/systemd/system/gogs.service
+ sudo systemctl daemon-reload
+ final_path=/opt/gogs
+ sudo rm -rf /opt/gogs
+ sudo rm -rf /opt/gogs_src
+ sudo rm -rf /etc/logrotate.d/gogs
+ sudo service rsyslog restart
+ sudo rm -rf /var/log/gogs
+ sudo userdel gogs
+ sudo rm -rf /home/gogs
+ sudo rm -rf /home/yunohost.app/gogs
+ mysql -u root '-p<passwd> -e 'DROP DATABASE gogs ; DROP USER gogs@localhost ;'
+ sudo yunohost service remove gogs
Warning: Unknown service 'gogs'
+ sudo rm -f /etc/nginx/conf.d/<domain.tld>.d/gogs.conf
+ sudo service nginx reload
+ sudo yunohost app ssowatconf
The SSOwat configuration has been generated
Error: Installation failed
```

Could be closed once YnH 2.4 will be handled.

**Comment by mbugeia** [comment]
Well this was kind of expected. I have a working version that use the helpers and fix most of the issue of this repo (#27 #29 #33 #34 #35 #36 #37 #40 #41 #43), I just need to handle the update from the current version. install, remove, backup and restore are already tested.
I will try to finish this weekend.

**Comment by M5oul** [comment]
Nice. It would be great, if you could publish that work in a `dev` branch, for instance.
I broked my Gogs instance since a long time ago. I don't really know what happen.

**Comment by Queueless** [comment]
Any ETA on a working installation for yunohost 2.4?  I've upgraded without realizing I would break this and now I'm stuck...

**Comment by mbugeia** [comment]
Hi, I still have some issues with the build. In go, it's difficult to build a specific version (=not master). In fact the working version I did have is not working anymore with the last gogs development and I don't know why.

I'm really considering getting back to the pre builded binary for the packages. Because of theses facts:
- It doesn't need to install golang (and gogs need the golang version of debian backports)
- Building gogs download more than 150Mb (!) of dependencies + the git repo, binaries are only ~15Mb
- There are binaries for the most commons architecture (amd64, i386, arm, raspberry 2)
- It much much simple and faster to install

What do you think ? @M5oul @julienmalik

**Comment by Josue-T** [comment]
I think since arm gogs binaries are available it shoud be better to use the binaries and not build it.

**Comment by mbugeia** [comment]
If you want to test, I've pushed my code here: https://github.com/mbugeia/gogs_ynh_binary
Everything works for me, the only thing that is not handled is the upgrade from the current package so don't try it ;)

**Comment by Queueless** [comment]
I tried: `sudo yunohost app install https://github.com/mbugeia/gogs_ynh_binary`

It didn't work for me: Here's a snippet from the yunohost-cli.log:

> 2016‐08‐15 18:51:41,428 INFO moulinette.actionsmap process ‐ processing action [12991.1]: yunohost.app.install
> 2016‐08‐15 18:51:41,437 INFO yunohost.app _fetch_app_from_git ‐ [12991.1] Downloading...
> 2016‐08‐15 18:51:41,995 INFO yunohost.app _extract_app_from_file ‐ [12991.1] Extracting...
> 2016‐08‐15 18:51:42,010 INFO yunohost.app _extract_app_from_file ‐ [12991.1] Done.
> 2016‐08‐15 18:52:05,124 INFO yunohost.hook hook_exec ‐ [12991.1] Executing script '/var/cache/yunohost/from_file/gogs_ynh_bin
> ary‐master/scripts/install'...
> 2016‐08‐15 18:52:05,229 INFO yunohost.hook <lambda> ‐ [12991.1] + set ‐eu
> 2016‐08‐15 18:52:05,234 INFO yunohost.hook <lambda> ‐ [12991.1] + domain=*****
> 2016‐08‐15 18:52:05,235 INFO yunohost.hook <lambda> ‐ [12991.1] + path=/gogs
> 2016‐08‐15 18:52:05,235 INFO yunohost.hook <lambda> ‐ [12991.1] + admin=*****
> 2016‐08‐15 18:52:05,236 INFO yunohost.hook <lambda> ‐ [12991.1] + is_public=Yes
> 2016‐08‐15 18:52:05,237 INFO yunohost.hook <lambda> ‐ [12991.1] + source ./_common.sh
> 2016‐08‐15 18:52:05,238 INFO yunohost.hook <lambda> ‐ [12991.1] ++ APPNAME=gogs
> 2016‐08‐15 18:52:05,238 INFO yunohost.hook <lambda> ‐ [12991.1] ++ VERSION=0.9.71
> 2016‐08‐15 18:52:05,240 INFO yunohost.hook <lambda> ‐ [12991.1] ++ case $(arch) in
> 2016‐08‐15 18:52:05,240 INFO yunohost.hook <lambda> ‐ [12991.1] +++ arch
> 2016‐08‐15 18:52:05,244 INFO yunohost.hook <lambda> ‐ [12991.1] ++ case $(arch) in
> 2016‐08‐15 18:52:05,245 INFO yunohost.hook <lambda> ‐ [12991.1] ++ echo 'Unable to detect your achitecture'
> 2016‐08‐15 18:52:05,245 INFO yunohost.hook <lambda> ‐ [12991.1] Unable to detect your achitecture
> 2016‐08‐15 18:52:05,246 INFO yunohost.hook <lambda> ‐ [12991.1] ++ exit 1
> 2016‐08‐15 18:52:05,281 INFO yunohost.hook hook_exec ‐ [12991.1] Executing script '/var/cache/yunohost/from_file/gogs_ynh_bin
> ary‐master/scripts/remove'...
> 2016‐08‐15 18:52:05,377 INFO yunohost.hook <lambda> ‐ [12991.1] + source ./_common.sh
> 2016‐08‐15 18:52:05,378 INFO yunohost.hook <lambda> ‐ [12991.1] ++ APPNAME=gogs
> 2016‐08‐15 18:52:05,379 INFO yunohost.hook <lambda> ‐ [12991.1] ++ VERSION=0.9.71
> 2016‐08‐15 18:52:05,381 INFO yunohost.hook <lambda> ‐ [12991.1] ++ case $(arch) in
> 2016‐08‐15 18:52:05,381 INFO yunohost.hook <lambda> ‐ [12991.1] +++ arch
> 2016‐08‐15 18:52:05,385 INFO yunohost.hook <lambda> ‐ [12991.1] ++ case $(arch) in
> 2016‐08‐15 18:52:05,386 INFO yunohost.hook <lambda> ‐ [12991.1] ++ echo 'Unable to detect your achitecture'
> 2016‐08‐15 18:52:05,386 INFO yunohost.hook <lambda> ‐ [12991.1] Unable to detect your achitecture
> 2016‐08‐15 18:52:05,387 INFO yunohost.hook <lambda> ‐ [12991.1] ++ exit 1
> 2016‐08‐15 18:52:05,422 WARNING yunohost.app app_install ‐ [12991.1] gogs has not been properly removed
> 2016‐08‐15 18:52:05,429 ERROR yunohost cli ‐ Installation failed
> 2016‐08‐15 18:53:44,405 INFO moulinette.actionsmap process ‐ processing action [13050.1]: yunohost.app.remove
> 2016‐08‐15 18:53:44,406 ERROR yunohost cli ‐ https://github.com/mbugeia/gogs_ynh_binary is not installed

**Comment by mbugeia** [comment]
@Queueless can you give me the result of the "arch" command on your system ? Also wich architecture are you using ?

**Comment by Queueless** [comment]
@mbugeia 
arch yields i686
I'm running yunohost on an old Acer AspireOne netbook with an Atom N270

**Comment by mbugeia** [comment]
@Queueless Ok, I've just pushed a fix to detect i686 as i386, this should work since both are 32 bits.

**Comment by Queueless** [comment]
@mbugeia That did, thanks!

**Comment by Queueless** [comment]
@mbugeia, if I wanted to change the location of the repositories, is there a simple way to do that?

**Comment by mbugeia** [comment]
@Queueless the location on the disk ? No, everything is in /home/gogs. Changing it would also mean changing the backup/restore path.

**Comment by mbugeia** [comment]
Fixed on the new repo https://github.com/YunoHost-Apps/gogs_ynh
