### ISSUE TITLE
Message d'erreur lors de l'installation

### ISSUE THREAD

**Issue by Ackak** [YunoHost-Apps/gogs_ynh_old#5]
Bonjour

J'ai testé l'installation et j'ai eu un message d'erreur :
E: Le pilote pour la méthode /usr/lib/apt/methods/https n'a pu être trouvé.

En regardant sur Internet, il a fallut que j'ajoute le paquet suivant manuellement :
apt-transport-https

J'ai ensuite recommencer l'installation sans soucis.

**Comment by mbugeia** [comment]
Hum chez moi ce paquet a l'air d'être installé par défaut dans yunohost.

A vérifier.

**Comment by mbugeia** [comment]
Bug confirmé il faut bien ajouter la dépendance ;)

**Comment by Shnoulle** [comment]
Fix don't fix : https://github.com/mbugeia/gogs_ynh/issues/7
